### ISSUE TITLE
Problem with MultiPhase

### ISSUE THREAD

**Issue by galleon** [junzis/openap-top#2]
I got the following issue when trying to use MultiPhase

Here is the problem I am facing:
```
openap-top git:(galleon/fixdoc) ✗ python test/my_example.py
Define optimizer...
Traceback (most recent call last):
  File "test/my_example.py", line 36, in <module>
    flight = optimizer.trajectory(objective=("ci:90", "ci:10", "ci:20"))  # Multiphase
  File "/Users/alleon_g/.pyenv/versions/scikit-decide/lib/python3.8/site-packages/openap/top/full.py", line 410, in trajectory
    d = np.sqrt(np.sum(((dfde.iloc[0] - dfcr.iloc[-1]) ** 2).values[1:3]))
  File "/Users/alleon_g/.pyenv/versions/scikit-decide/lib/python3.8/site-packages/pandas/core/indexing.py", line 931, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/Users/alleon_g/.pyenv/versions/scikit-decide/lib/python3.8/site-packages/pandas/core/indexing.py", line 1566, in _getitem_axis
    self._validate_integer(key, axis)
  File "/Users/alleon_g/.pyenv/versions/scikit-decide/lib/python3.8/site-packages/pandas/core/indexing.py", line 1500, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```

**Comment by galleon** [comment]
Not a problem anymore.
